version: "3.10"

services:
  data-generator-app:
    build:
      context: .
      dockerfile: src/main/docker/Dockerfile.jvm
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - QUARKUS_DATASOURCE_DB-KIND=mysql
      - QUARKUS_DATASOURCE_USERNAME=${PROD_MYSQL_USERNAME}
      - QUARKUS_DATASOURCE_PASSWORD=${PROD_MYSQL_PASSWORD}
      - QUARKUS_DATASOURCE_JDBC_URL=jdbc:mysql://mysql:3306/${PROD_MYSQL_DB}?enabledTLSProtocols=TLSv1.2
      - QUARKUS_HIBERNATE-ORM_DATABASE_GENERATION=update
      - TOTAL_PERSON_TOBE_GENERATED=${TOTAL_PERSON_TOBE_GENERATED}
      - DATA_GENERATOR_MAX_THREAD=${GENERATOR_MAX_THREAD}
      - DATA_GENERATOR_RECORDS_PER_THREAD=${GENERATOR_RECORDS_PER_THREAD}
      - DATA_GCP_API_KEY=${GCP_API_KEY}
      - KEYCLOAK_SERVER-BASE-URL=${KEYCLOAK_SERVER_BASE_URL}
      - KEYCLOAK_REALM-NAME=${KEYCLOAK_REALM_NAME}
      - QUARKUS_OIDC_CLIENT-ID=${KEYCLOAK_CLIENT_ID}
      - QUARKUS_OIDC_CREDENTIALS_SECRET=${KEYCLOAK_CLIENT_SECRET}
      - QUARKUS_OIDC_TLS_VERIFICATION=none
      - KEYCLOAK_USER_USERNAME=admin
      - KEYCLOAK_USER_PASSWORD=admin
      - QUARKUS_SSL_NATIVE=true
      - QUARKUS_TLS_TRUST-ALL=true
    ports:
      - "8008:8080"
    volumes:
      - ./:/build/
    networks:
      - mysql-network
      - keycloak_network
    depends_on:
      mysql:
        condition: service_healthy

  mysql:
    image: mysql:8.0
    restart: unless-stopped
    environment:
      - MYSQL_DATABASE=${PROD_MYSQL_DB}
      - MYSQL_USER=${PROD_MYSQL_USERNAME}
      - MYSQL_PASSWORD=${PROD_MYSQL_PASSWORD}
      - MYSQL_RANDOM_ROOT_PASSWORD=true
    ports:
      - "3360:3306"
    volumes:
      - mysqldb:/var/lib/mysql
    networks:
      - mysql-network
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10

volumes:
  mysqldb:

networks:
  mysql-network:
    driver: bridge
  keycloak_network:
    driver: bridge